
chatgpt:
  api-key: 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   #your api-key. It can be generated in this link https://beta.openai.com/docs/quickstart/adjust-your-settings
  max-tokens: 1000
